# Copyright (C) 2026 Sam Dornan
# This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

name: Build and Push PVE Thesis Monitor

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # Required permissions for pushing to GitHub Container Registry
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Source SBOM
        run: |
          curl -Lo $RUNNER_TEMP/sbom-tool https://github.com/microsoft/sbom-tool/releases/latest/download/sbom-tool-linux-x64
          chmod +x $RUNNER_TEMP/sbom-tool
          
          # Adjusted namespace to point to GitHub
          $RUNNER_TEMP/sbom-tool generate -b ./log-monitor -bc ./log-monitor -pn PVEThesisMonitor -pv 1.0.0 -ps InfrastructureTeam -nsb https://github.com/${{ github.repository }}/sbom/pve-thesis-monitor -V Verbose

      - name: Upload SBOM Artifact
        uses: actions/upload-artifact@v7
        with:
          name: source-sbom-manifest
          path: ./log-monitor/_manifest
      
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/pve-push-monitor
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./log-monitor
          platforms: linux/amd64
          push: true
          sbom: true
          provenance: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}